---

- name: clean up devstack VM
  hosts: all
  remote_user: "{{ regular_user }}"

  tasks:

  - name: destroy the devstack VM
    command: vagrant destroy -f
    args:
      chdir: "{{ ansible_env.HOME }}/workspace/Vagrant"

  - name: run Vagrant on target to launch devstack VM
    command: vagrant up --no-provision
    args:
      chdir: "{{ ansible_env.HOME }}/workspace/Vagrant"

  - name: install and run devstack on the VM
    command: vagrant provision
    args:
      chdir: "{{ ansible_env.HOME }}/workspace/Vagrant"

  - name: fetch admin credentials file
    command: ansible ubuntu-devstack -m fetch -a 'src=adminrc dest=adminrc flat=true'
    args:
      chdir: "{{ ansible_env.HOME }}/workspace/Vagrant"
    register: result
    changed_when: result.rc ==0 and result.stdout | regex_findall('changed.* true')

  - name: fetch demo credentials file
    command: ansible ubuntu-devstack -m fetch -a 'src=demorc dest=demorc flat=true'
    args:
      chdir: "{{ ansible_env.HOME }}/workspace/Vagrant"
    register: result
    changed_when: result.rc ==0 and result.stdout | regex_findall('changed.* true')

