---

- name: "regenerate manila csi secrets"
  hosts: all
  remote_user: "{{ regular_user }}"

  tasks:

  - name: clean up old csi-manila-secrets
    command: kubectl delete -f csi-manila-secrets.yaml
    register: result
    changed_when: result.rc == 0
    failed_when: result.rc != 0 and not result.stderr|regex_search('NotFound')
    args:
      chdir: workspace/src/k8s.io/cloud-provider-openstack

  - name: generate csi-manila-secrets
    shell: |
      source "{{ ansible_env.HOME }}/workspace/Vagrant/demorc"
      #source  "{{ ansible_env.HOME }}/workspace/Vagrant/adminrc"
      cat << YAML | kubectl create -f -
          apiVersion: v1
          kind: Secret
          metadata:
            name: csi-manila-secrets
            namespace: default
          stringData:
            os-authURL: "$OS_AUTH_URL"
            os-region: "$OS_REGION_NAME"
            os-userName: "$OS_USERNAME"
            os-password: "$OS_PASSWORD"
            os-projectName: "$OS_PROJECT_NAME"
            os-domainID: "$OS_USER_DOMAIN_ID"
      YAML
