---
- hosts: all

  tasks:

  - name: refresh apt cache
    command: "sudo apt-get update"

  - name: install base packages
    become: yes
    package:
      state: latest
      name: "{{ packages }}"
    vars:
      - packages:
        - aptitude

  - name: update packages
    become: yes
    package:
      state: latest
      name: "*"

  - name: install packages
    become: yes
    package:
      state: latest
      name: "{{ packages }}"
    vars:
      - packages:
        - python3
        - nfs-common
        - git
        - tmux
        - wget
        - net-tools
        - vim
        - haveged
        - python3-dev

  # VMs need good source of entropy
  - name: ensure haveged is started
    become: yes
    systemd:
      name: haveged
      enabled: yes
      masked: no
      state: started

  - name: clone devstack
    git: repo=https://git.openstack.org/openstack-dev/devstack
         dest={{ ansible_env.HOME }}/devstack
         update=no

  - name: setup local.conf
    action: copy
      src=local.conf
      dest={{ ansible_env.HOME }}/devstack/local.conf
      mode=0644
      owner={{ansible_env.USER}}

  # remove system packages that interfere with devstack's pip installs
  - name: uninstall conflicting system packages
    become: yes
    package:
      name: "{{ packages }}"
      state: absent
    vars:
      - packages:
        - python-setuptools
        - python3-httplib2
        - python3-pyasn1-modules

  - name: check if manila-share service is already running
    command: systemctl status devstack@m-shr
    failed_when: false
    register: result

  # devstack is not really idempotent and there is really no
  # guarantee that re-running it will help if the share service
  # isn't running but at least we ensure not to run it again if
  # manila share service is running
  - name: run devstack
    command: "{{ ansible_env.HOME }}/devstack/stack.sh"
    when: result.rc != 0

  - name: generate admin credentials
    shell: |
      source ./devstack/openrc admin admin
      env | awk '/^OS_/{printf "export %s\n", $0}' > adminrc
    args:
      executable: /bin/bash

  - name: generate demo credentials
    shell: |
      source ./devstack/openrc demo demo
      env | awk '/^OS_/{printf "export %s\n", $0}' > demorc
    args:
      executable: /bin/bash
