# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|

  config.vm.define "ubuntu-devstack" do |node|
    node.vm.hostname = "ubuntu-devstack"
    node.vm.box = "generic/ubuntu1804"
    node.vm.box_check_update = false
    node.vm.network "private_network", ip: "192.168.18.16"
    node.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 2
      domain.nested = true
      domain.cpu_mode = "host-passthrough"
    end
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible-provisioner.yml"
      ansible.verbose = 'v'
      ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
    end
  end
end
